### ISSUE TITLE
reverse_dns function needs error checking

### ISSUE THREAD

**Issue by deadbits** [yolothreat/utilitybelt#63]
reverse_dns will throw herror "Unknown host" exceptions on IP addresses that don't have a PTR record.

```
>>> import utilitybelt as ub
>>> ub.reverse_dns('1.54.140.138')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 3, in reverse_dns
herror: [Errno 1] Unknown host
>>> print "why python gods why!"
why python gods why!
```

**Comment by sroberts** [comment]
Yeah, that's probably a fairly good point.

**Comment by deadbits** [comment]
I can make a PR to patch this later today. Just wanted to have the issue in for reference when I do :)

**Comment by krmaxwell** [comment]
:+1:
